### ISSUE TITLE
[Purchase] Nissin pasta, 12x

### ISSUE THREAD

**Issue by Artoria2e5** [Elethom/bunnysden#3]
## Items to Purchase

| Brand | Model | Specs | Count | Est. Price | Link |
|:--|:--|:--|--:|--:|:--|
| 日清 | 意面 | 芝士培根风味 | 6 | - |   |
| 日清 | 意面 | 意式海鲜风味 | 6 | - |   |
| Total |   |   | 12 | CN¥ 65.5 |   |

## Purpose

Researches say it's unwise to think about buying grocery when hungry, but my stomach is really missing a big blast of pasta with generic powdered parmesan.

## Stage

- [x] purchased
- [x] received

**Comment by Elethom** [comment]
@Artoria2e5 
Need to list the flavours you want here for the record.

**Comment by Artoria2e5** [comment]
defly cream bacon. bolognese is meh/okay-ish. never tried the seafood one before, can take one or two.

**Comment by Elethom** [comment]
Wrong flavour but works. Closing.
