### ISSUE TITLE
Replace Dyson V6’s battery

### ISSUE THREAD

**Issue by Elethom** [Elethom/bunnysden#4]
Update:
Warranty still valid. Using official channel. 

Service No: 2317244
Pickup No: 288075698741
Return No: SF1013084195795

Stage:
- [x] contacting
- [x] send
- [x] receive

> 您好，我们会安排顺丰在2天左右上门取件寄到维修站检测，麻烦您将【收主机+充电器+主吸头】用旧报纸简单包装一下
> 发票请自行保存。
> 如检测为保修范围外的故障，我们会与您电话联系确认维修费用。
> 稍后系统会自动推送给您一个服务单号，您可凭此单号确认后续维修进度。

> 故障描述：电池红灯
> 解决方案：更换电池
> 交付性测试：运行测试正常

**Comment by Artoria2e5** [comment]
@luvletter might know some good 18650 deals.

**Comment by Elethom** [comment]
@Artoria2e5 Warranty still valid. Going through the official channel.

**Comment by Elethom** [comment]
Sent.

**Comment by Elethom** [comment]
Closing as done.
